import type { ColorLabel, OccasionId, Size, StyleId } from "./data";

export type Gender = "men" | "women";
export type Slot = "top" | "bottom" | "dress" | "outer" | "accessory";

export interface Product {
  id: string;
  /** UNIQLO product code, e.g. E480054-000. */
  productId: string;
  name: string;
  nameTh: string;
  /** "unisex" items can be picked for either gender. */
  gender: Gender | "unisex";
  slot: Slot;
  price: number;
  /** null = one size (bags, belts, caps). */
  sizes: readonly Size[] | null;
  styles: StyleId[];
  occs: OccasionId[];
  colors: ColorLabel[];
  image: string;
}

const p = (
  id: string,
  productId: string,
  name: string,
  nameTh: string,
  gender: Product["gender"],
  slot: Slot,
  price: number,
  sizes: Product["sizes"],
  styles: StyleId[],
  occs: OccasionId[],
  colors: ColorLabel[],
): Product => ({ id, productId, name, nameTh, gender, slot, price, sizes, styles, occs, colors, image: `/products/${id}.webp` });

// Names, prices, sizes, colours and photos come from the UNIQLO Thailand store
// (www.uniqlo.com/th). Fetched once and checked in; see tools/ in the project notes.
export const PRODUCTS: Product[] = [
  p("w-u-crew-neck-t-shirt", "E424873-000", "U Crew Neck T-Shirt", "เสื้อยืด U คอกลม", "women", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["budget", "class", "interview", "weekend"], ["White", "Black", "Beige", "Green", "Blue"]),
  p("w-mini-t-shirt", "E465760-000", "Mini T-Shirt", "เสื้อยืด ทรงมินิ", "women", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart", "trendy"], ["budget", "class", "interview", "weekend"], ["White", "Grey", "Black", "Beige"]),
  p("w-airism-cotton-t-shirt", "E465755-000", "AIRism Cotton T-Shirt", "เสื้อยืด AIRism ผ้าคอตตอน", "women", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("w-denim-boxy-shirt-half-sleeve", "E483877-000", "Denim Boxy Shirt | Half Sleeve", "เสื้อเชิ้ต ผ้าเดนิม ทรง Boxy | แขน 1/2", "women", "top", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart", "trendy"], ["class", "weekend"], ["Grey", "White", "Blue"]),
  p("w-soft-knitted-fleece-crew-neck-t-shirt", "E470143-000", "Soft Knitted Fleece Crew Neck T-Shirt", "เสื้อยืด ผ้าฟลีซ ขนนุ่ม คอกลม", "women", "top", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "smart"], ["budget", "class", "weekend"], ["White", "Grey", "Black", "Beige", "Blue"]),
  p("w-ultra-stretch-airism-uv-protection-full-zip-hoodie", "E483281-000", "Ultra Stretch AIRism UV Protection Full-Zip Hoodie", "เสื้อฮู้ด Ultra Stretch AIRism กันยูวี UV Protection มีซิป", "women", "top", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "sporty"], ["class", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("w-ribbed-henley-neck-t-shirt-long-sleeve", "E487908-000", "Ribbed Henley Neck T-Shirt | Long Sleeve", "เสื้อยืด ผ้าลายนูน (Ribbed) คอกระดุม | แขนยาว", "women", "top", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["budget", "class", "interview", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("w-premium-linen-shirt", "E475647-000", "Premium Linen Shirt", "เสื้อเชิ้ต ผ้าพรีเมียมลินิน", "women", "top", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart"], ["class", "interview", "travel", "weekend"], ["White", "Beige", "Green", "Blue"]),
  p("w-linen-blend-blouse-sleeveless", "E483890-000", "Linen Blend Blouse | Sleeveless", "เสื้อเบลาส์ ผ้าลินินผสม | แขนกุด", "women", "top", 590, ["XS", "S", "M", "L", "XL"] as const, ["smart"], ["budget", "interview", "travel", "weekend"], ["White", "Black", "Green"]),
  p("w-ultra-stretch-active-t-shirt", "E483458-000", "Ultra Stretch Active T-Shirt", "เสื้อยืด Ultra Stretch Active", "women", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Black", "Beige", "Blue"]),
  p("w-rayon-blouse", "E479071-000", "Rayon Blouse", "เสื้อเชิ้ต ผ้าเรยอน", "women", "top", 790, ["M", "L"] as const, ["smart"], ["interview", "weekend"], ["White", "Black"]),
  p("w-airism-sleeveless-top", "E457912-000", "AIRism Sleeveless Top", "เสื้อแขนกุด AIRism", "women", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["budget", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Blue"]),
  p("w-rib-mini-t-shirt", "E484457-000", "Rib Mini T-Shirt", "เสื้อยืด ผ้าลายนูน (Ribbed) ทรงมินิ", "women", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart", "trendy"], ["budget", "class", "interview", "weekend"], ["White", "Beige", "Blue"]),
  p("w-polo-sweater-short-sleeve", "E484607-000", "Polo Sweater | Short Sleeve", "เสื้อโปโลสเวตเตอร์ | แขนสั้น", "women", "top", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["class", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("w-front-open-shell-top-t-shirt-sleeveless", "E484226-000", "Front Open Shell Top T-Shirt | Sleeveless", "เสื้อยืด คอปิด กระดุมหน้า | แขนกุด", "women", "top", 390, ["XS", "S", "XL", "XXL"] as const, ["smart"], ["budget", "class", "interview", "weekend"], ["White", "Beige", "Green"]),
  p("w-ribbed-bra-top", "E473982-000", "Ribbed Bra Top", "เสื้อแขนกุด ผ้าลายนูน (Ribbed) เสริมบรา", "women", "top", 590, ["XS", "XXL"] as const, ["minimal"], ["budget", "weekend"], ["Black"]),
  p("w-oxford-boxy-shirt-striped", "E485265-000", "Oxford Boxy Shirt | Striped", "เสื้อเชิ้ต ผ้าอ๊อกฟอร์ด ทรง Boxy | ลายทาง", "women", "top", 990, ["L", "XL"] as const, ["relaxed", "smart"], ["class", "weekend"], ["Blue"]),
  p("w-rayon-skipper-collar-blouse-3-4-sleeve", "E479073-000", "Rayon Skipper Collar Blouse | 3/4 Sleeve", "เสื้อเบลาส์ ผ้าเรยอน ปกสกิปเปอร์ | แขน 3/4", "women", "top", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart"], ["interview", "weekend"], ["White", "Black", "Blue"]),
  p("w-ultra-stretch-active-jogger-pants", "E455942-000", "Ultra Stretch Active Jogger Pants", "กางเกง จ็อกเกอร์ Ultra Stretch Active", "women", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["class", "travel", "weekend"], ["Grey", "Black", "White", "Blue"]),
  p("w-linen-blend-easy-pants", "E473791-000", "Linen Blend Easy Pants", "กางเกง Easy ผ้าลินินผสม", "women", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["class", "travel", "weekend"], ["Black", "White", "Beige", "Green", "Blue"]),
  p("w-linen-cotton-shorts", "E473696-000", "Linen Cotton Shorts", "กางเกงขาสั้น ผ้าลินินคอตตอน", "women", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "smart"], ["travel", "weekend"], ["White", "Black", "Beige", "Green"]),
  p("w-cotton-relaxed-ankle-pants", "E482243-000", "Cotton Relaxed Ankle Pants", "กางเกง ผ้าคอตตอน ขา 5 ส่วน ทรงหลวม", "women", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "smart"], ["class", "interview", "weekend"], ["Black", "White", "Beige", "Green"]),
  p("w-ultra-stretch-active-wide-pants", "E474481-000", "Ultra Stretch Active Wide Pants", "กางเกง Ultra Stretch Active ขากว้าง", "women", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "sporty"], ["class", "travel", "weekend"], ["Grey", "Black", "Beige"]),
  p("w-smart-ankle-pants-regular-length-64-68-cm", "E479298-000", "Smart Ankle Pants | Regular Length 64 - 68 cm*", "กางเกง Smart ขา 5 ส่วน | ความยาว 64 - 68 cm*", "women", "bottom", 1290, ["XS"] as const, ["smart"], ["class", "interview", "weekend"], ["Beige"]),
  p("w-pleated-skort", "E480302-000", "Pleated Skort", "กระโปรง กางเกง จับจีบ", "women", "bottom", 790, ["M", "L"] as const, ["smart", "trendy"], ["class", "weekend"], ["White"]),
  p("w-denim-shorts", "E483512-000", "Denim Shorts", "กางเกงขาสั้น ผ้าเดนิม", "women", "bottom", 790, null, ["relaxed", "trendy"], ["weekend"], ["White", "Blue"]),
  p("w-ultra-stretch-active-biker-shorts", "E483295-000", "Ultra Stretch Active Biker Shorts", "กางเกงขาสั้น Ultra Stretch Active Biker", "women", "bottom", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "sporty"], ["budget", "travel", "weekend"], ["Grey", "Black", "Beige", "Blue"]),
  p("w-ezy-wide-straight-jeans-normal-length-73-77-cm", "E482281-000", "EZY Wide Straight Jeans | Normal Length 73 - 77 cm*", "ยีนส์ EZY ทรงกว้าง ขาตรง | ความยาวปกติ 73 - 77 cm*", "women", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed"], ["class", "weekend"], ["Grey", "Blue"]),
  p("w-baggy-jeans", "E483999-000", "Baggy Jeans", "ยีนส์ ทรง Baggy", "women", "bottom", 1290, null, ["relaxed"], ["class", "weekend"], ["Blue"]),
  p("w-cotton-culotte-length-50-54-cm", "E483042-000", "Cotton Culotte (Length 50 - 54 cm*)", "กางเกง Culotte ผ้าคอตตอน (ความยาว 50 - 54 cm*)", "women", "bottom", 1290, ["S", "M", "L", "XL"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("w-cotton-easy-shorts", "E482646-000", "Cotton Easy Shorts", "กางเกงขาสั้น Easy ผ้าคอตตอน", "women", "bottom", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed"], ["budget", "travel", "weekend"], ["Black", "Beige"]),
  p("w-cotton-volume-easy-pants", "E487589-000", "Cotton Volume Easy Pants", "กางเกง Easy ผ้าคอตตอน ทรงวอลลุ่ม", "women", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "trendy"], ["class", "travel", "weekend"], ["Grey", "Black", "Beige", "Green"]),
  p("w-linen-blend-easy-shorts", "E485251-000", "Linen Blend Easy Shorts", "กางเกงขาสั้น Easy ผ้าลินินผสม", "women", "bottom", 590, ["S", "M", "L", "XL"] as const, ["relaxed", "smart"], ["budget", "travel", "weekend"], ["White", "Beige", "Blue"]),
  p("w-straight-jeans-2026-model", "E482279-000", "Straight Jeans | 2026 Model", "ยีนส์ ทรงตรง | รุ่นปี 2026", "women", "bottom", 1290, null, ["relaxed"], ["class", "weekend"], ["Blue"]),
  p("w-smart-pants-normal-length-63-67-cm", "E487958-000", "Smart Pants | Normal Length 63 - 67 cm*", "กางเกง Smart | ความยาวปกติ 63 - 67 cm*", "women", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart"], ["class", "interview", "weekend"], ["Grey", "Black", "Beige", "Blue"]),
  p("w-ultra-stretch-airism-dress-sleeveless", "E482982-000", "Ultra Stretch AIRism Dress | Sleeveless", "ชุดกระโปรง AIRism Ultra Stretch | แขนกุด", "women", "dress", 990, ["XS", "S", "M", "L", "XL"] as const, ["sporty"], ["travel", "weekend"], ["White", "Black", "Beige", "Green"]),
  p("w-oversized-t-shirt-dress-short-sleeeve", "E484003-000", "Oversized T-shirt Dress | Short Sleeeve", "ชุดกระโปรง ทรงหลวม | แขนสั้น", "women", "dress", 990, ["S"] as const, ["relaxed", "smart"], ["class", "weekend"], ["Blue"]),
  p("w-washable-ribbed-knit-dress-sleeveless", "E488722-000", "Washable Ribbed Knit Dress | Sleeveless", "ชุดกระโปรง ผ้าถักลายนูน (Ribbed Knit) | แขนกุด", "women", "dress", 1290, ["XS", "S", "M", "L", "XL"] as const, ["minimal", "smart"], ["class", "interview", "weekend"], ["Grey", "Black", "Beige"]),
  p("w-combination-tiered-dress-sleeveless", "E487286-000", "Combination Tiered Dress | Sleeveless", "ชุดกระโปรง Tiere Combination | แขนกุด", "women", "dress", 1290, ["XS", "S", "M", "L", "XL"] as const, ["minimal"], ["weekend"], ["White", "Black", "Blue"]),
  p("w-cotton-blend-volume-sleeve-dress-short-sleeve", "E487279-000", "Cotton Blend Volume Sleeve Dress | Short Sleeve", "ชุดกระโปรง ผ้าคอตตอนผสม แขนมีวอลลุ่ม | แขนสั้น", "women", "dress", 1490, ["XS", "S", "M", "L", "XL"] as const, ["minimal", "trendy"], ["weekend"], ["Black", "Beige", "Blue"]),
  p("w-relaxed-dress-short-sleeve-printed", "E489217-000", "Relaxed Dress | Short Sleeve, Printed", "ชุดกระโปรง ทรงหลวม | แขนสั้น, มีลาย", "women", "dress", 1490, ["S"] as const, ["relaxed", "trendy"], ["weekend"], []),
  p("w-seersucker-shirt-dress-short-sleeve", "E483833-000", "Seersucker Shirt Dress | Short Sleeve", "ชุดกระโปรง Seersucker | แขนสั้น", "women", "dress", 1490, ["M"] as const, ["smart"], ["class", "weekend"], ["White"]),
  p("w-double-face-knit-dress-sleeveless", "E488186-000", "Double Face Knit Dress | Sleeveless", "ชุดกระโปรง ผ้าถัก Double Face | แขนกุด", "women", "dress", 1490, ["S", "M", "L"] as const, ["smart"], ["class", "interview", "weekend"], ["Black", "Beige"]),
  p("w-fluffy-yarn-fleece-full-zip-jacket", "E449753-000", "Fluffy Yarn Fleece Full-Zip Jacket", "เสื้อแจ็คเก็ต ผ้าฟลีซ ขนนุ่ม มีซิป", "women", "outer", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed"], ["weekend"], ["White", "Black", "Beige", "Green", "Blue"]),
  p("w-uv-protection-crew-neck-cardigan", "E465484-000", "UV Protection Crew Neck Cardigan", "เสื้อคาร์ดิแกน กันยูวี UV Protection คอกลม", "women", "outer", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart", "sporty"], ["class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green"]),
  p("w-pufftech-parka", "E469871-000", "PUFFTECH Parka", "เสื้อฮู้ดพาร์กา PUFFTECH", "women", "outer", 1990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["travel", "weekend"], ["Grey", "Black", "White", "Blue"]),
  p("w-reversible-parka", "E481602-000", "Reversible Parka", "เสื้อฮู้ดพาร์กา ใส่ได้ 2 ด้าน", "women", "outer", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["travel", "weekend"], ["Black", "Beige", "Blue"]),
  p("w-pocketable-uv-protection-parka-nanodesign", "E485671-000", "Pocketable UV Protection Parka (NANODESIGN)", "เสื้อฮู้ดพาร์กา กันยูวี UV Protection พับเก็บได้ (NANODESIGN)", "women", "outer", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["travel", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("w-pointelle-cardigan-printed", "E485717-000", "Pointelle Cardigan | Printed", "เสื้อคาร์ดิแกน ผ้าถัก (Pointelle) | มีลาย", "women", "outer", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart", "trendy"], ["class", "weekend"], ["White", "Beige", "Blue"]),
  p("w-seamless-down-parka", "E478577-000", "Seamless Down Parka", "เสื้อฮู้ดพาร์กา Down ขนเป็ด ไร้ตะเข็บ", "women", "outer", 3490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["travel", "weekend"], ["White", "Black", "Beige", "Blue"]),
  p("w-pocketable-uv-protection-parka-checked-nanodesign", "E485672-000", "Pocketable UV Protection Parka | Checked (NANODESIGN)", "เสื้อฮู้ดพาร์กา กันยูวี UV Protection พับเก็บได้ | ลายตาราง (NANODESIGN)", "women", "outer", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["travel", "weekend"], ["Beige"]),
  p("w-double-breasted-jacket", "E478557-000", "Double Breasted Jacket", "เสื้อแจ็คเก็ต กระดุมสองแถว", "women", "outer", 1990, ["XS", "L", "XL", "XXL"] as const, ["minimal"], ["interview", "weekend"], ["Grey", "Black", "Beige"]),
  p("w-merino-crew-neck-cardigan", "E469411-000", "Merino Crew Neck Cardigan", "เสื้อคาร์ดิแกน ผ้าเมอริโน่ คอกลม", "women", "outer", 990, ["S", "M", "L", "XL"] as const, ["minimal", "smart"], ["class", "interview", "weekend"], ["White", "Grey", "Black", "Beige", "Blue"]),
  p("w-ribbed-v-neck-cardigan", "E488014-000", "Ribbed V Neck Cardigan", "เสื้อคาร์ดิแกน ผ้าลายนูน (Ribbed) คอวี", "women", "outer", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["budget", "class", "interview", "weekend"], ["Grey", "Black"]),
  p("w-clean-belt", "E473471-000", "Clean Belt", "เข็มขัดหนัง", "women", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("w-vintage-belt", "E473470-000", "Vintage Belt", "เข็มขัด วินเทจ", "women", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("w-reversible-holeless-narrow-belt", "E483727-000", "Reversible Holeless Narrow Belt", "เข็มขัด แบบไม่เจาะรู ใส่ได้สองด้าน", "women", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("w-holeless-belt", "E481660-000", "Holeless Belt", "เข็มขัด ไม่เจาะรู", "women", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black"]),
  p("w-suede-long-belt", "E487800-000", "Suede Long Belt", "เข็มขัด หนังกลับ แบบยาว", "women", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Beige"]),
  p("w-cashmere-scarf", "E486760-000", "Cashmere Scarf", "ผ้าพันคอ ผ้าแคชเมียร์", "women", "accessory", 1490, null, ["minimal"], ["weekend"], ["White", "Grey", "Black", "Beige", "Blue"]),
  p("m-open-collar-shirt-short-sleeve", "E464938-000", "Open Collar Shirt | Short Sleeve", "เสื้อเชิ้ต คอเปิด | แขนสั้น", "men", "top", 790, ["XS", "S"] as const, ["smart"], ["class", "weekend"], ["White", "Black"]),
  p("m-airism-crew-neck-t-shirt", "E454312-000", "AIRism Crew Neck T-Shirt", "เสื้อยืด AIRism คอกลม", "men", "top", 390, ["XS"] as const, ["minimal", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Blue"]),
  p("m-airism-cotton-crew-neck-t-shirt", "E474244-000", "AIRism Cotton Crew Neck T-Shirt", "เสื้อยืด AIRism คอตตอน คอกลม", "men", "top", 390, ["XS", "S", "M", "L"] as const, ["minimal", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("m-super-non-iron-shirt-slim-fit-semi-wide-collar", "E456591-000", "Super Non Iron Shirt | Slim Fit, Semi Wide Collar", "เสื้อเชิ้ต Super Non Iron | ทรงเข้ารูป, ปกกว้าง", "men", "top", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["class", "interview", "weekend"], ["White", "Blue"]),
  p("m-airism-v-neck-t-shirt", "E454311-000", "AIRism V Neck T-Shirt", "เสื้อยืด AIRism คอวี", "men", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Black", "Beige"]),
  p("m-dry-ex-t-shirt", "E467145-000", "DRY-EX T-shirt", "เสื้อยืด DRY-EX", "men", "top", 490, ["XS"] as const, ["smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("m-u-airism-cotton-oversized-t-shirt-striped", "E484508-000", "U AIRism Cotton Oversized T-Shirt | Striped", "เสื้อยืด U AIRism คอตตอน ทรงหลวม | ลายทาง", "men", "top", 490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Blue"]),
  p("m-airism-cotton-pique-full-open-polo-shirt", "E482303-000", "AIRism Cotton Pique Full Open Polo Shirt", "เสื้อโปโล AIRism คอตตอน ปิเก้ คอเปิด", "men", "top", 790, ["XS"] as const, ["minimal", "smart", "sporty"], ["class", "interview", "travel", "weekend"], ["White", "Black", "Green", "Blue"]),
  p("m-merino-crew-neck-sweater", "E450535-000", "Merino Crew Neck Sweater", "เสื้อสเวตเตอร์ ผ้าเมอริโน่ คอกลม", "men", "top", 1290, ["S", "M", "L", "XL"] as const, ["minimal", "relaxed", "smart"], ["class", "interview", "travel", "weekend"], ["Grey", "Black", "Beige", "Green", "Blue"]),
  p("m-cotton-linen-stand-collar-shirt-short-sleeve", "E474528-000", "Cotton Linen Stand Collar Shirt | Short Sleeve", "เสื้อเชิ้ต ผ้าคอตตอนลินิน คอตั้ง | แขนสั้น", "men", "top", 790, ["XS", "M", "L", "XL"] as const, ["minimal", "smart"], ["class", "travel", "weekend"], ["Black", "Green"]),
  p("m-super-non-iron-stretch-shirt-slim-fit-regular-collar", "E473532-000", "Super Non Iron Stretch Shirt | Slim Fit, Regular Collar", "เสื้อเชิ้ต Super Non Iron ผ้ายืด | ทรงเข้ารูป, ปกธรรมดา", "men", "top", 1290, ["XS", "S"] as const, ["smart"], ["class", "interview", "travel", "weekend"], ["Blue"]),
  p("m-denim-shirt", "E484245-000", "Denim Shirt", "เสื้อเชิ้ต ผ้าเดนิม", "men", "top", 990, ["S", "M", "L", "XL"] as const, ["smart", "trendy"], ["class", "weekend"], ["Blue"]),
  p("m-dry-ex-polo-shirt", "E485782-000", "DRY-EX Polo Shirt", "เสื้อโปโล DRY-EX", "men", "top", 790, ["XS", "S"] as const, ["smart", "sporty"], ["class", "interview", "travel", "weekend"], ["Blue"]),
  p("m-boxy-shirt-short-sleeve", "E482497-000", "Boxy Shirt | Short Sleeve", "เสื้อเชิ้ต ทรง Boxy | แขนสั้น", "men", "top", 790, ["S"] as const, ["relaxed", "smart"], ["class", "weekend"], ["Grey", "Black", "White"]),
  p("m-peanuts-ut-short-sleeve-graphic-t-shirt", "E485058-000", "PEANUTS UT (Short Sleeve Graphic T-Shirt)", "เสื้อยืดแขนสั้น PEANUTS UT", "men", "top", 490, ["S", "M", "L", "XL", "XXL"] as const, ["smart", "trendy"], ["budget", "class", "weekend"], ["White"]),
  p("m-cashmere-crew-neck-sweater", "E450543-000", "Cashmere Crew Neck Sweater", "เสื้อสเวตเตอร์ ผ้าแคชเมียร์ คอกลม", "men", "top", 2990, ["S", "M", "L", "XL"] as const, ["minimal", "relaxed", "smart"], ["class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("m-super-non-iron-slim-fit-long-sleeve-shirt-striped-regular-co", "E475908-000", "Super Non Iron Slim Fit Long Sleeve Shirt (Striped - Regular Collar)", "เสื้อเชิ้ต Super Non Iron แขนยาว ทรงเข้ารูป ลายทาง ปกธรรมดา", "men", "top", 1290, ["XS", "S", "M", "L", "XL"] as const, ["smart"], ["class", "interview", "weekend"], ["Blue"]),
  p("m-ukiyo-e-blue-ut-short-sleeve-graphic-t-shirt", "E485075-000", "Ukiyo-e Blue UT (Short Sleeve Graphic T-Shirt)", "เสื้อยืดแขนสั้น Ukiyo-e Blue UT", "men", "top", 490, ["XS"] as const, ["smart", "trendy"], ["budget", "class", "weekend"], ["White"]),
  p("m-miracle-air-pants-length-73-85-cm", "E447780-000", "Miracle Air Pants | Length 73 - 85 cm*", "กางเกง Miracle Air | ความยาว 73 - 85 cm*", "men", "bottom", 1290, null, ["minimal"], ["class", "weekend"], ["Grey", "Black", "Beige", "Blue"]),
  p("m-ultra-stretch-pants", "E475598-000", "Ultra Stretch Pants", "กางเกง ผ้ายืด Ultra Stretch", "men", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["class", "travel", "weekend"], ["Grey", "Black", "Beige", "Green", "Blue"]),
  p("m-straight-jeans-2025-model", "E479816-000", "Straight Jeans | 2025 Model", "ยีนส์ ทรงตรง | รุ่นปี 2025", "men", "bottom", 1290, null, ["relaxed"], ["class", "weekend"], ["Blue"]),
  p("m-sweat-pants", "E451648-000", "Sweat Pants", "กางเกงวอร์ม ผ้าสเวต", "men", "bottom", 990, ["XS", "XXL"] as const, ["relaxed"], ["class", "travel", "weekend"], ["Grey", "Blue"]),
  p("m-baggy-jeans", "E482868-000", "Baggy Jeans", "ยีนส์ ทรง Baggy", "men", "bottom", 1290, null, ["relaxed"], ["class", "weekend"], ["White", "Grey", "Black", "Blue"]),
  p("m-sweat-wide-shorts", "E476225-000", "Sweat Wide Shorts", "กางเกงขาสั้น ผ้าสเวต ทรงกว้าง", "men", "bottom", 790, ["XS"] as const, ["relaxed"], ["class", "travel", "weekend"], ["Black", "Blue"]),
  p("m-linen-blend-easy-shorts", "E482260-000", "Linen Blend Easy Shorts", "กางเกงขาสั้น Easy ผ้าลินินผสม", "men", "bottom", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["budget", "travel", "weekend"], ["Black", "White", "Beige", "Green", "Blue"]),
  p("m-smart-ankle-pants", "E482886-000", "Smart Ankle Pants", "กางเกง Smart ขา 5 ส่วน", "men", "bottom", 1290, ["XS", "S", "XL", "XXL"] as const, ["smart"], ["class", "interview", "weekend"], ["Grey", "Beige", "Blue"]),
  p("m-linen-blend-easy-ankle-pants", "E478670-000", "Linen Blend Easy Ankle Pants", "กางเกง Easy ผ้าลินินผสม ขา 5 ส่วน", "men", "bottom", 790, ["S", "M", "XL"] as const, ["relaxed", "smart"], ["class", "interview", "travel", "weekend"], ["Black", "Green", "Blue"]),
  p("m-cargo-shorts", "E482942-000", "Cargo Shorts", "กางเกงขาสั้น Cargo", "men", "bottom", 790, ["XS", "S", "M"] as const, ["relaxed"], ["weekend"], ["Beige", "Green", "Blue"]),
  p("m-linen-blend-relaxed-pants", "E482920-000", "Linen Blend Relaxed Pants", "กางเกง ผ้าลินินผสม ทรงหลวม", "men", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["class", "travel", "weekend"], ["White", "Beige", "Green", "Blue"]),
  p("m-slim-straight-jeans", "E482856-000", "Slim Straight Jeans", "ยีนส์ ทรงเข้ารูป ขาตรง", "men", "bottom", 1290, null, ["relaxed"], ["class", "weekend"], ["Grey", "Blue"]),
  p("m-ultra-stretch-active-jogger-pants", "E485744-000", "Ultra Stretch Active Jogger Pants", "กางเกง Ultra Stretch Active Jogger", "men", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["class", "travel", "weekend"], ["Grey", "Black", "Beige", "Blue"]),
  p("m-ultra-stretch-sweat-shorts", "E485856-000", "Ultra Stretch Sweat Shorts", "กางเกงขาสั้น Ultra Stretch ผ้าสเวต", "men", "bottom", 590, ["XS", "S", "M", "L"] as const, ["relaxed", "sporty"], ["budget", "class", "travel", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("m-2way-stretch-smart-pants-normal-length-76-cm", "E487216-000", "2WAY Stretch Smart Pants | Normal Length 76 cm*", "กางเกง Smart ยืด 2 ทิศทาง (2WAY Stretch) | ความยาวปกติ 76 cm*", "men", "bottom", 1290, null, ["smart"], ["class", "interview", "travel", "weekend"], ["Grey", "Black", "Blue"]),
  p("m-miracle-air-jacket", "E448034-000", "Miracle Air Jacket", "เสื้อแจ็คเก็ต Miracle Air", "men", "outer", 1990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["interview", "weekend"], ["Grey", "Black", "Blue"]),
  p("m-pufftech-parka", "E470118-000", "PUFFTECH Parka", "เสื้อฮู้ดพาร์กา PUFFTECH", "men", "outer", 1990, ["XS", "S", "XXL"] as const, ["minimal"], ["travel", "weekend"], ["White", "Black", "Blue"]),
  p("m-zip-up-blouson", "E484249-000", "Zip Up Blouson", "เสื้อ Blouson มีซิป", "men", "outer", 1490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["weekend"], ["Beige", "Green", "Blue"]),
  p("m-reversible-parka", "E475037-000", "Reversible Parka", "เสื้อฮู้ดพาร์กา ใส่ได้ 2 ด้าน", "men", "outer", 1490, ["XS"] as const, ["minimal"], ["travel", "weekend"], ["Black", "Blue"]),
  p("m-zip-up-short-blouson", "E478230-000", "Zip Up Short Blouson", "เสื้อ Blouson มีซิป ทรงสั้น", "men", "outer", 1790, ["XS", "XXL"] as const, ["minimal"], ["weekend"], ["Black", "Beige", "Green"]),
  p("m-seamless-down-parka", "E470077-000", "Seamless Down Parka", "เสื้อฮู้ดพาร์กา Down ขนเป็ด ไร้ตะเข็บ", "men", "outer", 3490, ["XS"] as const, ["sporty"], ["travel", "weekend"], ["Beige", "Blue"]),
  p("m-premium-linen-shirt-jacket", "E483829-000", "Premium Linen Shirt Jacket", "เสื้อเชิ้ต เสื้อแจ็คเก็ต ผ้าพรีเมียมลินิน", "men", "outer", 2490, ["S"] as const, ["smart"], ["class", "interview", "travel", "weekend"], ["Grey", "Black"]),
  p("m-pufftech-vest", "E487348-000", "PUFFTECH Vest", "เสื้อกั๊ก PUFFTECH", "men", "outer", 1490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["weekend"], ["Black", "Beige", "Green", "Blue"]),
  p("m-pufftech-jacket", "E486171-000", "PUFFTECH Jacket", "เสื้อแจ็คเก็ต PUFFTECH", "men", "outer", 1790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["interview", "weekend"], ["Black", "Beige", "Green", "Blue"]),
  p("m-merino-blended-shirt-collar-cardigan", "E487488-000", "Merino Blended Shirt Collar Cardigan", "เสื้อคาร์ดิแกน ผ้าเมอริโน่ผสม คอปก", "men", "outer", 1490, ["S", "M", "L", "XL"] as const, ["minimal", "smart"], ["class", "interview", "weekend"], ["Black", "Green", "Blue"]),
  p("m-padded-shirt-jacket", "E489492-000", "Padded Shirt Jacket", "เสื้อเชิ้ตแจ็คเก็ต บุนวม", "men", "outer", 1990, ["S", "M", "L"] as const, ["smart"], ["class", "interview", "weekend"], ["Beige"]),
  p("m-italian-oiled-leather-belt", "E463730-000", "Italian Oiled Leather Belt", "เข็มขัดหนังอิตาเลี่ยน", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("m-italian-leather-stitched-belt", "E463729-000", "Italian Leather Stitched Belt", "เข็มขัดหนังอิตาเลี่ยน", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("m-italian-leather-slide-buckle-belt", "E481626-000", "Italian Leather Slide Buckle Belt", "เข็มขัด หนังอิตาเลี่ยน หัวแบบเลื่อน", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("m-leather-mesh-belt", "E481623-000", "Leather Mesh Belt", "เข็มขัดหนัง แบบตาข่าย", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("m-leather-combination-belt-striped", "E484783-000", "Leather Combination Belt | Striped", "เข็มขัดหนังผสม | ลายทาง", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Green"]),
  p("m-suede-belt", "E488047-000", "Suede Belt", "เข็มขัด หนังกลับ", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("m-italian-leather-garrison-belt", "E486184-000", "Italian Leather Garrison Belt", "เข็มขัด หนังอิตาลี หัวเหลี่ยม สไตล์วินเทจ", "men", "accessory", 990, ["M", "L"] as const, ["minimal"], ["weekend"], ["Black", "Beige"]),
  p("u-u-crew-neck-t-shirt", "E422992-000", "U Crew Neck T-Shirt", "เสื้อยืด U คอกลม", "unisex", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["budget", "class", "interview", "weekend"], ["White", "Grey", "Black", "Beige", "Blue"]),
  p("u-u-airism-cotton-oversized-crew-neck-t-shirt", "E465185-000", "U AIRism Cotton Oversized Crew Neck T-Shirt", "เสื้อยืด U AIRism คอตตอน คอกลม ทรงหลวม", "unisex", "top", 490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-dry-color-crew-neck-t-shirt", "E465187-000", "Dry Color Crew Neck T-shirt", "เสื้อยืด Dry Color คอกลม", "unisex", "top", 190, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-supima-cotton-t-shirt", "E455365-000", "SUPIMA Cotton T-Shirt", "เสื้อยืด SUPIMA ผ้าคอตตอน คอกลม", "unisex", "top", 490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["budget", "class", "interview", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-airism-cotton-pique-polo-shirt", "E475367-000", "AIRism Cotton Pique Polo Shirt", "เสื้อโปโล AIRism คอตตอน ผ้าปิเก้", "unisex", "top", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart", "sporty"], ["class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-dry-ex-uv-protection-full-zip-hoodie", "E465203-000", "DRY-EX UV Protection Full-Zip Hoodie", "เสื้อฮู้ด DRY-EX กันยูวี UV Protection มีซิป", "unisex", "top", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "sporty"], ["class", "travel", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("u-u-airism-cotton-crew-neck-t-shirt-long-sleeve", "E465193-000", "U AIRism Cotton Crew Neck T-Shirt | Long Sleeve", "เสื้อยืด U AIRism คอตตอน คอกลม | แขนยาว", "unisex", "top", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Black", "Beige", "Blue"]),
  p("u-dry-waffle-henley-neck-t-shirt", "E475361-000", "Dry Waffle Henley Neck T-Shirt", "เสื้อยืด Dry ผ้าวาฟเฟิล คอกระดุม", "unisex", "top", 490, ["XS"] as const, ["smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["Green"]),
  p("u-oxford-boxy-shirt", "E475718-000", "Oxford Boxy Shirt", "เสื้อเชิ้ต ผ้าออกฟอร์ด ทรง Boxy", "unisex", "top", 990, ["XL"] as const, ["relaxed", "smart"], ["class", "weekend"], ["White"]),
  p("u-dry-ex-t-shirt", "E482299-000", "DRY-EX T-Shirt", "เสื้อยืด DRY-EX", "unisex", "top", 490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["smart", "sporty"], ["budget", "class", "interview", "travel", "weekend"], ["White", "Grey", "Black", "Green", "Blue"]),
  p("u-boxy-cropped-t-shirt", "E487962-000", "Boxy Cropped T-Shirt", "เสื้อยืด Boxy ทรงครอป", "unisex", "top", 390, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart", "trendy"], ["budget", "class", "weekend"], ["White", "Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-cotton-linen-shirt-short-sleeve", "E477181-000", "Cotton Linen Shirt | Short Sleeve", "เสื้อเชิ้ต ผ้าคอตตอนลินิน | แขนสั้น", "unisex", "top", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["class", "travel", "weekend"], ["White", "Beige", "Green", "Blue"]),
  p("u-jersey-barrel-leg-pants-normal-length-70-72-cm", "E475344-000", "Jersey Barrel Leg Pants | Normal Length 70-72 cm*", "กางเกง ผ้าเจอร์ซี่ ขาบาร์เรล (Jersey Barrel) | ความยาวปกติ 70-72 cm*", "unisex", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["trendy"], ["class", "weekend"], ["White", "Black", "Beige", "Green"]),
  p("u-sweat-wide-pants", "E471809-000", "Sweat Wide Pants", "กางเกงวอร์ม ผ้าสเวต ทรงกว้าง", "unisex", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed"], ["class", "travel", "weekend"], ["Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-baggy-barrel-leg-jeans-shorter-length-70-cm", "E480740-000", "Baggy Barrel Leg Jeans | Shorter Length 70 cm*", "ยีนส์ ขาบาร์เรล (Baggy Barrel) | ความยาวพิเศษ - สั้นขึ้น 70 cm*", "unisex", "bottom", 1290, null, ["relaxed", "trendy"], ["class", "weekend"], ["White", "Grey", "Beige", "Blue"]),
  p("u-ezy-jeans", "E455476-000", "EZY Jeans", "ยีนส์ EZY", "unisex", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed"], ["class", "weekend"], ["Grey", "Black", "Beige", "Blue"]),
  p("u-ultra-stretch-active-tapered-pants", "E465491-000", "Ultra Stretch Active Tapered Pants", "กางเกง Ultra Stretch Active ทรงขาสอบ", "unisex", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["class", "travel", "weekend"], ["Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-ultra-stretch-active-shorts", "E475386-000", "Ultra Stretch Active Shorts", "กางเกงขาสั้น Ultra Stretch Active", "unisex", "bottom", 590, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "sporty"], ["budget", "travel", "weekend"], ["Grey", "Black", "Beige", "Green", "Blue"]),
  p("u-stretch-easy-ankle-pants-cotton-relaxed", "E479134-000", "Stretch Easy Ankle Pants (Cotton Relaxed)", "กางเกง ผ้าคอตตอน ขา 5 ส่วน ทรงหลวม (Stretch Easy)", "unisex", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "relaxed", "smart"], ["class", "interview", "travel", "weekend"], ["Grey", "Black", "Beige", "Green"]),
  p("u-smart-wide-straight-pants-normal-length-70-74-cm", "E487957-000", "Smart Wide Straight Pants | Normal Length 70 - 74 cm*", "กางเกง Smart ทรงกว้าง ขาตรง | ความยาวปกติ 70 - 74 cm*", "unisex", "bottom", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["class", "interview", "weekend"], ["White", "Grey", "Black"]),
  p("u-corduroy-easy-ankle-pants", "E486471-000", "Corduroy Easy Ankle Pants", "กางเกง Easy ผ้าลูกฟูก ขา 5 ส่วน", "unisex", "bottom", 790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart", "trendy"], ["class", "interview", "travel", "weekend"], ["White", "Black", "Beige", "Green", "Blue"]),
  p("u-stretch-easy-shorts", "E476081-000", "Stretch Easy Shorts", "กางเกงขาสั้น Easy ผ้ายืด", "unisex", "bottom", 590, ["XS"] as const, ["relaxed"], ["budget", "travel", "weekend"], ["Grey", "Black", "Beige"]),
  p("u-zip-up-short-jacket", "E479208-000", "Zip Up Short Jacket", "เสื้อแจ็คเก็ต มีซิป ทรงสั้น", "unisex", "outer", 1490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["weekend"], ["White", "Beige", "Blue"]),
  p("u-pocketable-uv-protection-parka-nanodesign", "E469292-000", "Pocketable UV Protection Parka (Nanodesign)", "เสื้อฮู้ดพาร์กา กันยูวี UV Protection พับเก็บได้ (NANODESIGN)", "unisex", "outer", 1290, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["sporty"], ["travel", "weekend"], ["Grey", "Black", "Green", "Blue"]),
  p("u-fleece-full-zip-jacket", "E450195-000", "Fleece Full-Zip Jacket", "เสื้อแจ็คเก็ต ผ้าฟลีซ มีซิป", "unisex", "outer", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed"], ["weekend"], ["Grey", "Black", "White", "Beige", "Green", "Blue"]),
  p("u-milano-ribbed-shirt-collar-cardigan", "E478550-000", "Milano Ribbed Shirt Collar Cardigan", "เสื้อคาร์ดิแกน ผ้ามิลาโน่ ลายนูน (Ribbed) คอปก", "unisex", "outer", 1490, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal", "smart"], ["class", "interview", "weekend"], ["Grey", "Black", "White", "Green", "Blue"]),
  p("u-harrington-jacket", "E484610-000", "Harrington Jacket", "เสื้อแจ็คเก็ต Harrington", "unisex", "outer", 1790, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["minimal"], ["interview", "weekend"], ["Black", "Beige", "Blue"]),
  p("u-hybrid-down-parka", "E478277-000", "Hybrid Down Parka", "เสื้อฮู้ดพาร์กา Hybrid Down", "unisex", "outer", 3490, ["XS"] as const, ["minimal"], ["travel", "weekend"], []),
  p("u-cotton-linen-shirt-jacket", "E482443-000", "Cotton Linen Shirt Jacket", "เสื้อเชิ้ตแจ็คเก็ต คอตตอนลินิน", "unisex", "outer", 1490, ["M"] as const, ["minimal", "smart"], ["class", "interview", "travel", "weekend"], ["Green"]),
  p("u-light-souffle-yarn-relaxed-cardigan", "E488839-000", "Light Souffle Yarn Relaxed Cardigan", "เสื้อคาร์ดิแกน Light Souffle Yarn ทรงหลวม", "unisex", "outer", 990, ["XS", "S", "M", "L", "XL", "XXL"] as const, ["relaxed", "smart"], ["class", "interview", "weekend"], ["White", "Grey", "Beige", "Green"]),
  p("u-round-mini-shoulder-bag-2026-model", "E481610-000", "Round Mini Shoulder Bag | 2026 Model", "กระเป๋าสะพายไหล่ ทรงมินิ | รุ่นใหม่ 2026", "unisex", "accessory", 590, null, ["trendy"], ["budget", "weekend"], ["White", "Grey", "Black", "Beige", "Green"]),
  p("u-reusable-bag-cotton", "E462191-000", "Reusable Bag (Cotton)", "กระเป๋าผ้า คอตตอน", "unisex", "accessory", 100, ["M", "L"] as const, ["minimal"], ["budget", "weekend"], ["White"]),
  p("u-drawstring-bag", "E483050-000", "Drawstring Bag", "กระเป๋า เชือกรูด", "unisex", "accessory", 790, null, ["minimal"], ["weekend"], ["Black", "Beige", "Blue"]),
  p("u-utility-shoulder-bag", "E488859-000", "Utility Shoulder Bag", "กระเป๋าสะพายไหล่ Utility", "unisex", "accessory", 990, null, ["minimal"], ["weekend"], ["Black", "Green"]),
  p("u-2-way-one-handle-bag", "E486771-000", "2 Way One Handle Bag", "กระเป๋า 2Way", "unisex", "accessory", 590, null, ["minimal"], ["budget", "weekend"], ["Black", "Beige", "Green"]),
  p("u-uv-protection-cap-2way-stretch", "E478306-000", "UV Protection Cap | 2WAY Stretch", "หมวก กันยูวี UV Protection | 2WAY Stretch", "unisex", "accessory", 590, null, ["sporty"], ["budget", "travel", "weekend"], ["Black"]),
  p("u-sunglasses-wellington-folding-standard-type", "E481639-000", "Sunglasses | Wellington Folding (Standard Type)", "แว่นตากันแดด | Wellington พับได้ (Standard Type)", "unisex", "accessory", 590, null, ["minimal"], ["budget", "weekend"], ["Black"]),
  p("u-gift-bag", "E484719-000", "Gift Bag", "ถุงของขวัญ", "unisex", "accessory", 130, ["S", "M", "L"] as const, ["minimal"], ["budget", "weekend"], ["White"]),
  p("u-uv-protection-knitted-bucket-hat", "E486196-000", "UV Protection Knitted Bucket Hat", "หมวก ผ้าถัก กันยูวี UV Protection", "unisex", "accessory", 590, null, ["smart", "sporty"], ["budget", "class", "travel", "weekend"], ["Black", "Blue"]),
  p("u-souffle-yarn-knitted-stole", "E489405-000", "Souffle Yarn Knitted Stole", "ผ้าพันคอ ผ้าถัก Souffle Yarn", "unisex", "accessory", 790, null, ["smart"], ["class", "weekend"], ["White", "Grey", "Beige", "Blue"]),
  p("u-jean-miachel-basquiat-uv-protection-cap", "E481430-001", "Jean-Miachel Basquiat UV Protection Cap", "หมวก Jean-Miachel Basquiat กันยูวี UV Protection", "unisex", "accessory", 590, null, ["sporty"], ["budget", "travel", "weekend"], ["Green"]),
];

const BY_ID = new Map(PRODUCTS.map((item) => [item.id, item]));

export const getProduct = (id: string) => BY_ID.get(id);

export const getProducts = (ids: readonly string[]) =>
  ids.map(getProduct).filter((item): item is Product => Boolean(item));
